server {
    listen 80;

    location / {
        # [핵심 변경] Dockerfile이 파일을 넣어둔 경로인 'dev' 폴더를 루트로 지정합니다.
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        # [중요] root가 이미 /dev 안으로 들어왔으므로, 여기서는 /dev를 뺍니다.
        # (즉, /usr/share/nginx/html/dev/index.html 을 찾으라는 뜻이 됩니다)
        try_files $uri $uri/ /index.html;
    }

    # 로그 설정
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}