server {
    listen 80;

    location / {
        # [핵심 변경] Dockerfile이 파일을 /dev 안에 숨겨놨으므로,
        # Nginx가 아예 그 안쪽을 '루트'로 인식하게 만듭니다.
        root   /usr/share/nginx/html/dev;
        index  index.html index.htm;

        # root가 이미 .../dev 로 설정되었기 때문에
        # 여기서는 /index.html 이라고만 적어도 실제로는 /dev/index.html을 찾아갑니다.
        try_files $uri $uri/ /index.html;
    }

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}